name: Build Flutter Mobile

on:
  push:
    branches:
      - main
    paths:
      - 'mobile/**'
  pull_request:
    branches:
      - main
    paths:
      - 'mobile/**'

jobs:
  build-flutter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - name: Install dependencies
        run: flutter pub get
        working-directory: mobile

      - name: Build APK release
        run: flutter build apk --release
        working-directory: mobile

      - name: List APK folder
        run: ls -la mobile/build/app/outputs/flutter-apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk-keris-penjual
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
