name: Build Flutter Mobile Pengguna

on:
  push:
    branches:
      - main
    paths:
      - 'mobile_pengguna/**'
  pull_request:
    branches:
      - main
    paths:
      - 'mobile_pengguna/**'

jobs:
  build-flutter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - name: Install dependencies
        run: flutter pub get
        working-directory: mobile_pengguna

      - name: Build APK release
        run: flutter build apk --release
        working-directory: mobile_pengguna

      - name: List APK folder
        run: ls -la mobile_pengguna/build/app/outputs/flutter-apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk-keris
          path: mobile_pengguna/build/app/outputs/flutter-apk/app-release.apk
