name: Build Flutter Mobile

on:
  push:
    branches:
      - main
    paths:
      - 'mobile/**'
  pull_request:
    branches:
      - main
    paths:
      - 'mobile/**'

permissions:
  contents: write

jobs:
  build-flutter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - name: Install dependencies
        run: flutter pub get
        working-directory: mobile

      - name: Build APK release
        run: flutter build apk --release
        working-directory: mobile

      - name: List APK folder
        run: ls -la mobile/build/app/outputs/flutter-apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk-keris-penjual
          path: mobile/build/app/outputs/flutter-apk/app-release.apk

      - name: Rename APK
        run: mv mobile/build/app/outputs/flutter-apk/app-release.apk mobile/build/app/outputs/flutter-apk/toko-keris-penjual.apk

      - name: Copy APK to backend/public/apk
        run: |
          mkdir -p backend/public/apk
          cp mobile/build/app/outputs/flutter-apk/toko-keris-penjual.apk backend/public/apk/

      - name: Commit and push APK to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add backend/public/apk/toko-keris-penjual.apk
          git commit -m "Update APK pengguna"
          for i in 1 2 3; do
          git push && break || {
            echo "Push failed, retrying in 5s..."
            sleep 5
            git pull origin main --rebase || true
          }
          done

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk-keris
          path: mobile/build/app/outputs/flutter-apk/toko-keris-penjual.apk
