name: Test FTP Access

on:
  workflow_dispatch:

jobs:
  test-ftp:
    runs-on: ubuntu-latest
    steps:
      - name: Test FTP port
        run: |
          timeout 10 bash -c "</dev/tcp/${{ secrets.FTP_HOST }}/21" && echo "✅ Port 21 terbuka" || echo "❌ Port 21 tidak bisa diakses"
