name: Build docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: docs

      - name: Build
        run: npm run build
        working-directory: docs

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-dist
          path: docs/dist

  ftp-deploy:
    name: Upload Docs to FTP
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-dist
          path: docs/dist

      - name: Upload docs via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST_FRONTEND }}
          username: ${{ secrets.FTP_USERNAME_FRONTEND }}
          password: ${{ secrets.FTP_PASSWORD_FRONTEND }}
          local-dir: docs/dist/
          server-dir: ${{ secrets.REMOTE_DIR }}
          protocol: ftp
          timeout: 120000